{% import '.cookiecutter_includes/license_header.j2' as license_macros with context %}
{{- license_macros.license_header(
  cookiecutter.license,
  cookiecutter.author,
  cookiecutter.project_slug,
  file_name='pre-commit-config.yaml',
  comment_style='hash') -}}
---
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=mdx]
      - id: mixed-line-ending
        args: [--fix=lf]
        {%- raw %}
      - id: check-yaml
        exclude: '{{ cookiecutter.project_slug }}/.*'
      - id: check-json
        exclude: '{{ cookiecutter.project_slug }}/.*'
      - id: check-toml
        exclude: '{{ cookiecutter.project_slug }}/.*'
        {% endraw %}
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-symlinks

  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        {%- raw %}
        exclude: '{{ cookiecutter.project_slug }}/.*'
        {% endraw %}

  - repo: local
    hooks:
      - id: generate-changelog
        name: Generate CHANGELOG.md
        entry: make changelog
        language: system
        files: CHANGELOG.md
        always_run: true
        pass_filenames: false

  - repo: local
    hooks:
      - id: generate-docs
        name: Generate Documentation
        entry: make build-docs
        language: system
        always_run: true
        pass_filenames: false

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.3.3
    hooks:
      - id: cspell
        stages: [commit-msg]
        args: ["--config", "./cspell.json"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
